abstract: Add plugin support to your Moose classes via roles.
author: Guillermo Roditi, <groditi@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: MooseX-Object-Pluggable
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Inspector: 1.04
  Moose: 0.17
version: 0.0004
